import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import { useRouter } from "expo-router";
import { Button, Card, c, Title } from "@/components/nexus";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/lib/auth-context";

export default function AccountSecurity() {
  const router = useRouter(); const { user, changePassword, submitting } = useAuth();
  const [currentPassword, setCurrentPassword] = useState(""); const [nextPassword, setNextPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [error, setError] = useState("");
  const save = async () => { if (!currentPassword || !nextPassword) { setError("Enter your current password and a new password."); return; } if (nextPassword !== confirmPassword) { setError("New passwords do not match."); return; } try { setError(""); const message = await changePassword(currentPassword, nextPassword); Alert.alert("Password changed", `${message} Please sign in again.`); router.replace("/login" as never); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to change password."); } };
  return <ScreenContainer><ScrollView contentContainerStyle={s.page}><Title eyebrow="Workspace protection" title="Account security" detail="Passwords stay server-side. Updating yours ends other active JWT sessions." /><Card><Text style={s.email}>{user?.email ?? "Workspace member"}</Text>{user?.must_change_password ? <Text style={s.required}>A temporary password is active. Choose a personal password now.</Text> : null}<Text style={s.label}>CURRENT PASSWORD</Text><TextInput value={currentPassword} onChangeText={setCurrentPassword} secureTextEntry style={s.input} placeholder="Current password" placeholderTextColor={c.muted} /><Text style={s.label}>NEW PASSWORD</Text><TextInput value={nextPassword} onChangeText={setNextPassword} secureTextEntry style={s.input} placeholder="12+ characters, with letters and numbers" placeholderTextColor={c.muted} /><Text style={s.label}>CONFIRM NEW PASSWORD</Text><TextInput value={confirmPassword} onChangeText={setConfirmPassword} secureTextEntry style={s.input} placeholder="Repeat new password" placeholderTextColor={c.muted} />{error ? <Text style={s.error}>{error}</Text> : null}<Button label="Change password" icon="key" onPress={() => void save()} loading={submitting} /></Card><Button secondary label="Back to workspace" icon="arrow-back" onPress={() => router.back()} /></ScrollView></ScreenContainer>;
}
const s = StyleSheet.create({ page: { padding: 18, gap: 14 }, email: { color: c.ink, fontSize: 15, fontWeight: "800", marginBottom: 12 }, required: { color: c.amber, backgroundColor: "#FFF7E5", padding: 10, borderRadius: 10, fontSize: 12, lineHeight: 17, marginBottom: 12 }, label: { color: c.muted, fontWeight: "900", fontSize: 10, letterSpacing: 0.8, marginTop: 9, marginBottom: 5 }, input: { minHeight: 46, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: c.border, color: c.ink, fontSize: 14 }, error: { color: c.red, fontSize: 12, lineHeight: 18, marginTop: 8, marginBottom: 2 } });
