import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, FlatList, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Button, Card, c, Pill, State, Title } from "@/components/nexus";
import { ScreenContainer } from "@/components/screen-container";
import { api, apiError, PaymentGateway, PaymentPlan, PaymentRecord } from "@/lib/api";

type BillingRow = { type: "gateway"; value: PaymentGateway } | { type: "payment"; value: PaymentRecord };
const readinessText = (gateway: PaymentGateway) => gateway.checkout_ready && gateway.webhook_ready ? "Checkout and signed webhook are configured" : "Platform configuration pending";
const price = (plan: PaymentPlan) => new Intl.NumberFormat(undefined, { style: "currency", currency: plan.currency, maximumFractionDigits: 2 }).format(plan.amount_minor / 100);

export default function Billing() {
  const router = useRouter(); const queryClient = useQueryClient(); const gateways = useQuery({ queryKey: ["payment-gateways"], queryFn: api.payments.gateways }); const plans = useQuery({ queryKey: ["payment-plans"], queryFn: api.payments.plans }); const history = useQuery({ queryKey: ["payments"], queryFn: api.payments.history });
  const startCheckout = async (gateway: PaymentGateway, plan: PaymentPlan) => {
    if (!gateway.checkout_ready || !gateway.webhook_ready) return Alert.alert("Configuration pending", "The platform operator must configure the provider credentials, webhook secret, and plan catalogue. No payment has been started.");
    if (gateway.provider === "razorpay") return Alert.alert("Razorpay checkout", "Razorpay orders are prepared server-side, but a native checkout sheet requires a signed development build with the Razorpay native SDK. No order has been created from this screen.");
    try { const result = await api.payments.checkout(gateway.provider, plan.code); void queryClient.invalidateQueries({ queryKey: ["payments"] }); if (!result.checkout_url) return Alert.alert("Checkout created", "The provider did not return a checkout URL. No payment is marked paid until its signed webhook is verified."); const supported = await Linking.canOpenURL(result.checkout_url); if (!supported) throw new Error("This device cannot open the provider’s secure checkout page."); await Linking.openURL(result.checkout_url); } catch (error) { Alert.alert("Checkout unavailable", apiError(error, "The secure provider checkout could not be started. No payment was completed.")); }
  };
  if (gateways.isLoading || plans.isLoading || history.isLoading) return <ScreenContainer><State title="Loading billing controls" loading /></ScreenContainer>;
  const rows: BillingRow[] = [...(gateways.data ?? []).map((value) => ({ type: "gateway" as const, value })), ...(history.data ?? []).map((value) => ({ type: "payment" as const, value }))];
  return <ScreenContainer><FlatList data={rows} keyExtractor={(item, index) => item.type === "gateway" ? `gateway-${item.value.provider}` : item.value.id ?? String(index)} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>‹ Workspace</Text></Pressable><Title eyebrow="TENANT BILLING" title="Payments" detail="Checkout creation and payment records are isolated to this workspace." /><Card><Text style={s.noticeTitle}>Safe by default</Text><Text style={s.notice}>The client never receives gateway secrets or chooses an amount. A server-owned plan catalogue and verified provider webhook control payment status.</Text></Card><Text style={s.section}>Gateway status</Text></View>} ListEmptyComponent={<State title="No billing data" detail="Refresh when workspace billing configuration becomes available." />} renderItem={({ item }) => item.type === "gateway" ? <GatewayCard gateway={item.value} plans={plans.data ?? []} onPlan={(plan) => void startCheckout(item.value, plan)} /> : <PaymentCard payment={item.value} />} ItemSeparatorComponent={() => <View style={s.separator} />} ListFooterComponent={<Text style={s.footnote}>A browser redirect is not payment confirmation. AiMarket records a payment only after it receives and verifies the provider’s signed webhook.</Text>} /></ScreenContainer>;
}

function GatewayCard({ gateway, plans, onPlan }: { gateway: PaymentGateway; plans: PaymentPlan[]; onPlan: (plan: PaymentPlan) => void }) {
  const ready = gateway.checkout_ready && gateway.webhook_ready && gateway.plans_configured; const tone = ready ? "green" : "amber";
  return <Card><View style={s.row}><View style={s.copy}><Text style={s.cardTitle}>{gateway.label}</Text><Text style={s.detail}>{readinessText(gateway)}</Text></View><Pill label={ready ? "READY" : "PENDING"} tone={tone} /></View><View style={s.statusRow}><Status label="Checkout" ready={gateway.checkout_ready} /><Status label="Webhook" ready={gateway.webhook_ready} /><Status label="Plans" ready={gateway.plans_configured} /></View>{ready && plans.length > 0 ? <View style={s.planBox}><Text style={s.planTitle}>Choose a configured plan</Text>{plans.map((plan) => <Button key={plan.code} compact secondary label={`${plan.name} · ${price(plan)}`} icon="open-in-new" onPress={() => onPlan(plan)} />)}</View> : <View style={s.action}><Button compact secondary label="Await platform configuration" icon="lock-outline" onPress={() => Alert.alert(gateway.label, "The provider configuration is incomplete. No payment can be initiated from this workspace.")} /></View>}</Card>;
}

function Status({ label, ready }: { label: string; ready: boolean }) { return <View style={s.status}><Text style={[s.dot, { color: ready ? c.green : c.amber }]}>●</Text><Text style={s.statusText}>{label}</Text></View>; }
function PaymentCard({ payment }: { payment: PaymentRecord }) { return <Card><View style={s.row}><View style={s.copy}><Text style={s.cardTitle}>{payment.plan_name ?? "Payment"}</Text><Text style={s.detail}>{payment.provider} · {payment.status.replaceAll("_", " ")}</Text></View><Pill label={payment.status.toUpperCase()} tone={payment.status === "paid" ? "green" : "amber"} /></View></Card>; }
const s = StyleSheet.create({ content: { padding: 20, paddingBottom: 34 }, header: { gap: 13, marginBottom: 18 }, back: { color: c.blue, fontSize: 14, fontWeight: "900" }, section: { color: c.ink, fontSize: 16, fontWeight: "900", marginTop: 3 }, noticeTitle: { color: c.ink, fontSize: 15, fontWeight: "900" }, notice: { color: c.muted, fontSize: 12, lineHeight: 18, marginTop: 6 }, row: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }, copy: { flex: 1 }, cardTitle: { color: c.ink, fontSize: 16, fontWeight: "900" }, detail: { color: c.muted, fontSize: 12, lineHeight: 18, marginTop: 4, textTransform: "capitalize" }, statusRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 13 }, status: { flexDirection: "row", alignItems: "center", gap: 4 }, dot: { fontSize: 12 }, statusText: { color: c.muted, fontSize: 11, fontWeight: "800" }, action: { marginTop: 13 }, planBox: { gap: 8, marginTop: 14 }, planTitle: { color: c.muted, fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7 }, separator: { height: 10 }, footnote: { color: c.muted, fontSize: 11, lineHeight: 17, textAlign: "center", marginTop: 18, paddingHorizontal: 14 } });
