import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Alert, FlatList, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Button, Card, c, State, Title } from "@/components/nexus";
import { Field } from "@/components/workflow";
import { knowledgePrinciples } from "@/lib/autonomous-marketing";
import { api } from "@/lib/api";

export default function Knowledge() { const sources = useQuery({ queryKey: ["brain-sources"], queryFn: api.brain.sources }); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState<Record<string, unknown> | null>(null); const [asking, setAsking] = useState(false); const ask = async () => { if (!question.trim()) { Alert.alert("Ask a business question", "Describe the decision, channel, or customer problem you want to understand."); return; } setAsking(true); try { setAnswer(await api.brain.query(question)); } catch { Alert.alert("Knowledge query unavailable", "Try again after reconnecting."); } finally { setAsking(false); } }; if (sources.isLoading) return <ScreenContainer><State title="Opening reusable knowledge" loading /></ScreenContainer>; return <ScreenContainer><FlatList data={answer ? Object.entries(answer) : []} keyExtractor={([key]) => key} contentContainerStyle={s.content} ListHeaderComponent={<><View style={s.header}><Title eyebrow="KNOWLEDGE-FIRST ENGINE" title="Operating memory" detail="Use approved evidence and prior learning first. Generate only when a new synthesis is required." /><View style={s.mode}><MaterialIcons name="memory" color="#9BC4FF" size={17} /><Text style={s.modeText}>{sources.data?.length ?? 0} stored sources available for evidence-led answers</Text></View></View><Card><Text style={s.cardTitle}>Ask before you create</Text><Text style={s.detail}>The fast path searches your business knowledge and saved decisions. It reduces repeated research and makes the next recommendation easier to audit.</Text><View style={s.form}><Field label="YOUR DECISION OR QUESTION" value={question} onChangeText={setQuestion} placeholder="Which CRM buyer problem should we lead with this month?" multiline /><Button label="Search operating memory" icon="psychology" onPress={ask} loading={asking} /></View></Card><Text style={s.section}>Knowledge-first rules</Text>{knowledgePrinciples.map((principle, index) => <View key={principle} style={s.principle}><View style={s.number}><Text style={s.numberText}>{index + 1}</Text></View><Text style={s.principleText}>{principle}</Text></View>)}{answer ? <Text style={s.section}>Evidence-led answer</Text> : null}</>} ListEmptyComponent={answer ? null : <State title="No answer opened yet" detail="Ask a focused question to retrieve approved business context before you generate new work." />} renderItem={({ item: [key, value] }) => <Card><Text style={s.answerKey}>{key.replaceAll("_", " ")}</Text><Text style={s.answerValue}>{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</Text></Card>} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} /></ScreenContainer>; }
const s = StyleSheet.create({ content: { padding: 20, paddingBottom: 34 }, header: { gap: 15, marginBottom: 18 }, mode: { backgroundColor: c.navy, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, flexDirection: "row", gap: 8, alignItems: "center", alignSelf: "flex-start" }, modeText: { color: "#C7DAFC", fontSize: 11, fontWeight: "800" }, cardTitle: { color: c.ink, fontSize: 16, fontWeight: "900" }, detail: { color: c.muted, fontSize: 13, lineHeight: 19, marginTop: 6 }, form: { gap: 11, marginTop: 14 }, section: { color: c.ink, fontSize: 16, fontWeight: "900", marginTop: 19, marginBottom: 11 }, principle: { flexDirection: "row", gap: 10, marginBottom: 11, alignItems: "flex-start" }, number: { width: 23, height: 23, borderRadius: 12, backgroundColor: c.sky, justifyContent: "center", alignItems: "center" }, numberText: { color: c.blue, fontSize: 11, fontWeight: "900" }, principleText: { color: c.ink, fontSize: 13, lineHeight: 19, flex: 1 }, answerKey: { color: c.blue, fontSize: 10, fontWeight: "900", letterSpacing: 0.8, textTransform: "uppercase" }, answerValue: { color: c.ink, fontSize: 13, lineHeight: 19, marginTop: 8 } });
