import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { Button, Card, c, money, Pill, State, Title } from "@/components/nexus";
import { Field } from "@/components/workflow";
import { api, Campaign } from "@/lib/api";
import { safeNumber } from "@/lib/market-utils";
export default function Campaigns() { const router = useRouter(); const client = useQueryClient(); const campaigns = useQuery({ queryKey: ["campaigns"], queryFn: api.campaigns.list }); const profile = useQuery({ queryKey: ["profile"], queryFn: api.profile.get }); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [channel, setChannel] = useState("Google Ads"); const [objective, setObjective] = useState("Generate qualified leads"); const [budget, setBudget] = useState(""); const [saving, setSaving] = useState(false); const create = async () => { if (!name || !budget) { Alert.alert("Add campaign details", "Name and budget are required."); return; } setSaving(true); try { await api.campaigns.create({ name, channel, objective, budget: safeNumber(budget) }); await client.invalidateQueries({ queryKey: ["campaigns"] }); await client.invalidateQueries({ queryKey: ["overview"] }); setOpen(false); setName(""); setBudget(""); } catch { Alert.alert("Campaign not created", "Please try again."); } finally { setSaving(false); } }; if (campaigns.isLoading) return <ScreenContainer><State title="Loading campaigns" loading /></ScreenContainer>; const currency = profile.data?.currency ?? "USD"; return <ScreenContainer><FlatList data={campaigns.data ?? []} keyExtractor={(item) => item._id} contentContainerStyle={s.content} ListHeaderComponent={<View style={s.header}><Title eyebrow="PAID MEDIA" title="Campaigns" detail="Track investment, outcomes, and daily performance." /><Button compact label="New" icon="add" onPress={() => setOpen(true)} /></View>} ListEmptyComponent={<State title="No campaigns yet" detail="Create a campaign to centralize performance tracking." />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/campaign/[id]", params: { id: item._id } } as never)}><CampaignCard item={item} currency={currency} /></Pressable>} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} /><Modal transparent visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={s.backdrop}><View style={s.sheet}><Text style={s.sheetTitle}>New campaign</Text><Field label="CAMPAIGN NAME" value={name} onChangeText={setName} placeholder="CRM launch – Search" /><Field label="CHANNEL" value={channel} onChangeText={setChannel} placeholder="Google Ads" /><Field label="OBJECTIVE" value={objective} onChangeText={setObjective} placeholder="Generate qualified leads" /><Field label="TOTAL BUDGET" value={budget} onChangeText={setBudget} placeholder="1500" numeric /><Button label="Create campaign" icon="add" onPress={create} loading={saving} /></View></View></Modal></ScreenContainer>; }
function CampaignCard({ item, currency }: { item: Campaign; currency: string }) { return <Card><View style={s.row}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.cardDetail}>{item.channel} · {item.objective}</Text></View><Pill label={item.status} tone={item.status === "Active" ? "green" : "amber"} /></View><View style={s.rule} /><View style={s.stats}><Text style={s.stat}>{money(item.budget, currency)}{`\n`}<Text style={s.statLabel}>BUDGET</Text></Text><Text style={s.stat}>{Number(item.roas ?? 0).toFixed(2)}x{`\n`}<Text style={s.statLabel}>ROAS</Text></Text><Text style={s.stat}>{item.conversions ?? 0}{`\n`}<Text style={s.statLabel}>CONVERSIONS</Text></Text></View></Card>; }
const s = StyleSheet.create({ content: { padding: 20, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 }, row: { flexDirection: "row", gap: 10 }, cardTitle: { color: c.ink, fontSize: 16, fontWeight: "900" }, cardDetail: { color: c.muted, fontSize: 12, marginTop: 4 }, rule: { height: 1, backgroundColor: c.border, marginVertical: 14 }, stats: { flexDirection: "row", justifyContent: "space-between" }, stat: { color: c.ink, fontSize: 14, fontWeight: "900" }, statLabel: { color: c.muted, fontSize: 9, fontWeight: "900" }, backdrop: { flex: 1, backgroundColor: "#0B122066", justifyContent: "flex-end" }, sheet: { backgroundColor: c.white, borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 20, paddingBottom: 34, gap: 12 }, sheetTitle: { color: c.ink, fontSize: 20, fontWeight: "900" } });
