import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { PropsWithChildren } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
export const c = { navy: "#0B1220", blue: "#2563EB", sky: "#EAF2FF", canvas: "#F7F9FC", ink: "#14213D", muted: "#64748B", border: "#DDE5F0", green: "#16A34A", amber: "#D97706", red: "#DC2626", white: "#FFFFFF" };
export const money = (value: unknown, currency = "USD") => { try { return new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value ?? 0)); } catch { return `${currency} ${Number(value ?? 0).toLocaleString()}`; } };
export function Card({ children }: PropsWithChildren) { return <View style={s.card}>{children}</View>; }
export function Title({ eyebrow, title, detail }: { eyebrow?: string; title: string; detail?: string }) { return <View><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.title}>{title}</Text>{detail ? <Text style={s.detail}>{detail}</Text> : null}</View>; }
export function Button({ label, onPress, icon, loading, secondary, danger, compact }: { label: string; onPress: () => void; icon?: React.ComponentProps<typeof MaterialIcons>["name"]; loading?: boolean; secondary?: boolean; danger?: boolean; compact?: boolean }) { return <Pressable onPress={onPress} disabled={loading} style={({ pressed }) => [s.button, compact && s.compact, secondary && s.secondary, danger && s.danger, pressed && s.pressed]}>{loading ? <ActivityIndicator color={secondary ? c.blue : c.white} /> : <>{icon ? <MaterialIcons name={icon} color={secondary ? c.blue : c.white} size={18} /> : null}<Text style={[s.buttonText, secondary && s.secondaryText]}>{label}</Text></>}</Pressable>; }
export function Pill({ label, tone = "blue" }: { label: string; tone?: "blue" | "green" | "amber" | "red" }) { const color = tone === "green" ? c.green : tone === "amber" ? c.amber : tone === "red" ? c.red : c.blue; return <View style={[s.pill, { backgroundColor: `${color}16` }]}><Text style={[s.pillText, { color }]}>{label}</Text></View>; }
export function State({ title, detail, loading }: { title: string; detail?: string; loading?: boolean }) { return <View style={s.state}>{loading ? <ActivityIndicator color={c.blue} /> : <MaterialIcons name="inbox" size={28} color={c.blue} />}<Text style={s.stateTitle}>{title}</Text>{detail ? <Text style={s.stateDetail}>{detail}</Text> : null}</View>; }
const s = StyleSheet.create({ card: { backgroundColor: c.white, borderRadius: 18, borderWidth: 1, borderColor: c.border, padding: 16, shadowColor: c.navy, shadowOpacity: 0.04, shadowRadius: 10, shadowOffset: { width: 0, height: 3 }, elevation: 1 }, eyebrow: { color: c.blue, fontSize: 10, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 5 }, title: { color: c.ink, fontSize: 27, lineHeight: 34, fontWeight: "900" }, detail: { color: c.muted, fontSize: 14, lineHeight: 20, marginTop: 4 }, button: { minHeight: 48, borderRadius: 13, backgroundColor: c.blue, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, paddingHorizontal: 16 }, compact: { minHeight: 38, borderRadius: 10, paddingHorizontal: 12 }, secondary: { backgroundColor: c.sky, borderWidth: 1, borderColor: "#C9DDFF" }, danger: { backgroundColor: c.red }, buttonText: { color: c.white, fontSize: 14, fontWeight: "900" }, secondaryText: { color: c.blue }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] }, pill: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4 }, pillText: { fontSize: 11, fontWeight: "900" }, state: { minHeight: 190, alignItems: "center", justifyContent: "center", padding: 24, gap: 8 }, stateTitle: { color: c.ink, fontSize: 16, fontWeight: "900" }, stateDetail: { color: c.muted, fontSize: 13, lineHeight: 19, textAlign: "center" } });
